name: Build and Deploy Flutter Web App

on:
  push:
    branches:
      - main  # 当 main 分支有新的提交时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable # or: beta, master (or main)
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter web
        run: flutter build web --wasm

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
